#!/bin/bash

#Update the system
sudo apt-get -y update
sudo apt-get -y upgrade

#Install Docker and Docker Compose
sudo apt-get install -y docker.io docker-compose

#Run mongoDB container for dauqu
# sudo docker run -d -p 27017:27017 --name dauqu-mongo --restart unless-stopped mongo

#Install MongoDB on Ubuntu
sudo apt-get install gnupg -y
curl -fsSL https://pgp.mongodb.com/server-6.0.asc | \
   sudo gpg -o /usr/share/keyrings/mongodb-server-6.0.gpg \
   --dearmor

echo "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-6.0.gpg ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/6.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-6.0.list

sudo apt-get update

sudo apt-get install -y mongodb-org

#Start mongoDB after reboot
sudo systemctl enable mongod
sudo systemctl start mongod



#Check if directory exists
if [ -d "/var/dauqu" ]; then
#Remove directory
    sudo rm -rf /var/dauqu
fi

#Create a directory for dauqu in /var/dauqu
sudo mkdir /var/dauqu
sudo mkdir /var/dauqu/dauqu-proxy
sudo mkdir /var/dauqu/dauqu-panel
sudo mkdir /var/dauqu/dauqu-panel/frontend


#Change directory to /var/dauqu
cd /var/dauqu/dauqu-panel

#Download file in dauqu directory
sudo wget https://get.dauqu.com/dauqu-panel/main

#Change permission
sudo chmod +x ./main

#Add dauqu systemctl service
sudo cat > /etc/systemd/system/dauqu-panel.service <<EOF
[Unit]
Description=dauqu Control Panel

[Service]
Type=simple
Restart=always
RestartSec=5s
ExecStart=/var/dauqu/dauqu-panel/main

[Install]
WantedBy=multi-user.target
EOF

#Enable dauqu service
sudo systemctl enable dauqu-panel

#Start dauqu service
sudo systemctl start dauqu-panel



#Change directory to /var/dauqu
cd /var/dauqu/dauqu-proxy

#Download file in dauqu directory
sudo wget https://get.dauqu.com/dauqu-proxy/main


#Change permission
sudo chmod +x ./main


#Add dauqu systemctl service
sudo cat > /etc/systemd/system/dauqu-proxy.service <<EOF
[Unit]
Description=dauqu Server

[Service]
Type=simple
Restart=always
RestartSec=5s
ExecStart=/var/dauqu/dauqu-proxy/main

[Install]
WantedBy=multi-user.target
EOF
 

#Download frontend zip file
sudo wget https://get.dauqu.com/build.zip
#Move file to /var/dauqu/dauqu-panel/frontend


#Intall unzip
sudo apt-get install -y unzip

sudo mv build.zip /var/dauqu/dauqu-panel/frontend/build.zip
#Unzip file
sudo unzip /var/dauqu/dauqu-panel/frontend/build.zip -d /var/dauqu/dauqu-panel/frontend

#Enable dauqu service
sudo systemctl enable dauqu-proxy

#Start dauqu service
sudo systemctl start dauqu-proxy


#Show message of success installation
echo "Dauqu installed successfully"
echo "Open your browser and go to http://your-hostname/ui"
echo "Enjoy!"



