#!/bin/bash

# Retry function
retry() {
  local n=1
  local max_attempts=3
  local delay=5
  while true; do
    "$@" && break || {
      if [[ $n -lt $max_attempts ]]; then
        ((n++))
        echo "Command failed. Attempt $n/$max_attempts:"
        sleep $delay;
      else
        echo "The command has failed after $n attempts."
        return 1
      fi
    }
  done
}

# Stop the frontend Docker container
retry sudo docker stop daucu_frontend
retry sudo docker rm daucu_frontend


# Run the updated frontend Docker image
retry sudo docker run -d --name daucu_frontend -p 3000:3000 --restart always daucu/daucu_frontend

# Download the updated Go executable for the backend
retry curl -o /usr/local/bin/daucu_backend https://get.daucu.com/backend/main

# Make the executable file executable
sudo chmod +x /usr/local/bin/daucu_backend

# Reload systemd to recognize the new service
retry sudo systemctl daemon-reload

# Enable and start the new backend service
retry sudo systemctl enable daucu_backend
retry sudo systemctl start daucu_backend

echo "Update completed successfully!"
